version: '3'
services:
  web:
    image: amazon/amazon-ecs-sample
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: sap-lab-ecs # Update With Value
        awslogs-region: us-west-2
        awslogs-stream-prefix: web